import { ACTIONS, bindingLabel, GAMEPAD_BUTTONS } from '../game/InputActions.js';
export const CONTROL_LABELS = { keyboard: 'Keyboard', mouse: 'Mouse', gamepad: 'Gamepad' };
const resolve = value => typeof value === 'string' ? { device: value === 'advanced' ? 'keyboard' : value, flightMode: value === 'advanced' ? 'manual' : 'assisted' } : value;
export function flightHints(value, freeFlight = false) {
  const settings = resolve(value), device = settings.device || settings.input;
  if (device === 'gamepad') return '<span><kbd>LS</kbd> PITCH / ROLL</span><span><kbd>D-PAD ↑ ↓</kbd> THROTTLE</span><span><kbd>LB RB</kbd> YAW</span><span><kbd>LT</kbd> BRAKE</span><span><kbd>MENU</kbd> PAUSE</span>';
  const actions = ['pitchUp','pitchDown','rollLeft','rollRight','throttleUp','throttleDown','afterburner','airBrake', ...(freeFlight ? ['landingAssist','tacticalMap'] : ['cannon','missile','targetNext','flare']), 'pause'];
  return (device === 'mouse' ? '<span><kbd>MOUSE</kbd> STEER</span>' : '') + actions.map(action => `<span><kbd>${bindingLabel(action,settings,false)}</kbd> ${ACTIONS[action].label.toUpperCase()}</span>`).join('');
}
export function beginnerGuide(value, full = false) {
  const settings = resolve(value), device = settings.device || settings.input, manual = settings.flightMode === 'manual';
  const key = action => bindingLabel(action, settings);
  return `<div class="guide-modes" aria-label="Input device">${Object.entries(CONTROL_LABELS).map(([id,label]) => `<button data-mode="${id}" aria-pressed="${id === device}">${label}</button>`).join('')}</div>
    <div class="guide-modes" aria-label="Flight assistance"><button data-flight-mode="assisted" aria-pressed="${!manual}">Assisted</button><button data-flight-mode="manual" aria-pressed="${manual}">Manual</button></div>
    <p class="guide-summary">${manual ? 'Manual flight keeps inertia and gives direct control. Manage pitch, roll and yaw independently.' : 'Assisted flight gently levels the aircraft when you release the controls and coordinates banking turns.'} Throttle holds where you set it.</p>
    <div class="arrow-guide"><div><kbd>${key('pitchUp')}</kbd> Nose up <kbd>${key('pitchDown')}</kbd> Nose down<br><kbd>${key('rollLeft')} / ${key('rollRight')}</kbd> Roll <kbd>${key('yawLeft')} / ${key('yawRight')}</kbd> Yaw / ground steer</div></div>
    ${device === 'mouse' ? `<p>Aim mouse toward the desired flight path. ${settings.mouseInvert ? 'Mouse Y is inverted.' : 'Move up to climb.'} ${settings.mouseLock ? 'Click the flight view to capture the mouse.' : 'Unlocked mouse steering uses the cursor position.'} <kbd>${key('recenter')}</kbd> recenters the virtual stick. Hold <kbd>${key('freeLook')}</kbd> to look without steering.</p>` : ''}
    ${device === 'gamepad' ? `<p>Standard controllers only. Left stick: pitch/roll; right stick: look. LB/RB: yaw, LT: brake, RT: cannon. D-pad up/down: throttle; left/right: map/gear. A: missile, B: flares, X: target, Y: camera; left-stick press: boost; menu: pause. Nonstandard mappings use keyboard/mouse fallback.</p>` : ''}
    <ol class="learn-steps"><li><b>Set power</b><span><kbd>${key('throttleUp')} / ${key('throttleDown')}</kbd> adjusts throttle. Releasing holds that setting. <kbd>${key('afterburner')}</kbd> boosts while held.</span></li><li><b>Take off deliberately</b><span>Build at least 200 km/h, then use the nose-up control to rotate. Cannon and boost do not rotate the aircraft.</span></li><li><b>Approach and land</b><span><kbd>${key('landingAssist')}</kbd> opens airbases. <kbd>${key('landingGear')}</kbd> lowers gear. Hold <kbd>${key('airBrake')}</kbd> for air/wheel braking. Reduce throttle before touchdown.</span></li></ol>
    ${full ? `<details class="combat-guide" open><summary>All effective controls</summary><div class="controls-grid">${Object.entries(ACTIONS).map(([id,action]) => `<div><kbd>${key(id)}</kbd><span>${action.label} · ${action.kind === 'held' || action.kind === 'axis' ? 'hold' : 'press'}</span></div>`).join('')}</div></details><p class="panel-footnote">Wait for LOCKED before launching a missile. Free Flight has no enemies or weapons. Keyboard bindings, controller calibration and assistance are available in Settings.</p><button data-action="keybindings" class="primary">Customize bindings</button>` : ''}`;
}
