import { escapeHTML } from './Accessibility.js';
import { threatState } from './ThreatDisplay.js';
import * as T from 'three';
/** Independent DOM per local seat: no duplicate global IDs, canvas or live gameplay ownership. */
export class SeatHUD {
  constructor(root,{seatId='2',label='PLAYER 2'}={}){this.root=root;this.seatId=String(seatId);this.el=root.ownerDocument.createElement('section');this.el.className='seat-hud';this.el.dataset.seat=this.seatId;this.el.setAttribute('aria-label',`${label} flight instruments`);this.el.innerHTML=`<div class="seat-heading"><b>${escapeHTML(label)}</b><span data-seat-field="objective"></span></div><div class="seat-flight"><span data-seat-field="speed"></span><span data-seat-field="altitude"></span></div><div class="seat-reticle" aria-hidden="true">＋</div><div class="seat-warning" data-seat-field="warning" role="status"></div><div class="seat-footer"><span data-seat-field="health"></span><span data-seat-field="weapons"></span><button type="button" data-seat-action="menu">SEAT MENU</button></div>`;root.appendChild(this.el);this.fields=Object.fromEntries([...this.el.querySelectorAll('[data-seat-field]')].map(el=>[el.dataset.seatField,el]));}
  update(game){const p=game.player;if(!p)return;const set=(k,v)=>{if(this.fields[k].textContent!==v)this.fields[k].textContent=v;};set('objective',game.openSkies?.snapshot?.().objective || game.mission?.name || 'FREE FLIGHT');set('speed',`${Math.round((p.speed || 0)*3.6)} KM/H`);set('altitude',`${Math.round(p.position.y)} M`);set('health',`${Math.round(p.hp || 0)} HP · ${Math.round((p.throttle || 0)*100)}% THR`);set('weapons',`MSL ${game.missilesLeft ?? 0} · GUN ${game.cannonLeft ?? 0} · FLR ${game.flaresLeft ?? 0}`);const urgent=threatState(game).find(c=>c.urgency>=3);set('warning',!p.alive?'AIRCRAFT LOST · SQUADMATE CAN CONTINUE':urgent?`${urgent.kind.toUpperCase()} · ${urgent.direction} ${urgent.altitude}`:p.stall?'STALL · INCREASE THROTTLE':'');
    if(!this.targetMarker){this.targetMarker=this.root.ownerDocument.createElement('div');this.targetMarker.className='seat-target';this.el.appendChild(this.targetMarker);this.projection=new T.Vector3();}
    const target=game.target,visible=target?.alive && (game.canDetect?.(p,target)??true);this.targetMarker.hidden=!visible;
    if(visible){this.projection.copy(target.position).project(game.camera);this.targetMarker.style.left=`${Math.max(7,Math.min(93,(this.projection.x+1)*50))}%`;this.targetMarker.style.top=`${Math.max(24,Math.min(78,(1-this.projection.y)*50))}%`;this.targetMarker.textContent=`◇ ${target.callsign || 'HOSTILE'} · ${(p.position.distanceTo(target.position)/1000).toFixed(1)} KM · ${game.lock>=1.4?'LOCKED':Math.round(game.lock/1.4*100)+'% LOCK'}`;this.targetMarker.dataset.locked=String(game.lock>=1.4);}
  }
  setViewport({left=0,top=0,width=100,height=100}={}){Object.assign(this.el.style,{left:`${left}%`,top:`${top}%`,width:`${width}%`,height:`${height}%`});}
  dispose(){this.el.remove();}
}
