import { performance } from 'node:perf_hooks';
import { MatchState } from './MatchState.js';
import { validateMissionPreset } from '../src/shared/MissionGenerator.js';
import { JET_MODELS, LIVERIES } from '../src/game/JetConfigs.js';
import { PROTOCOL_VERSION, MODES, SIMULATION_HZ, SNAPSHOT_HZ, MAX_BUFFERED_BYTES } from '../src/shared/Protocol.js';
const bounded=(v,f,min,max)=>Number.isFinite(v)?Math.max(min,Math.min(max,Math.round(v))):f;
export function safeOptions(input={},previous={}) {
  const raw={...previous,...input},mode=MODES.includes(raw.mode)?raw.mode:'1v1';const capacity=mode==='1v1'?2:mode==='2v2'||mode==='open_skies_coop'?4:mode==='3v3'?6:8;
  return {mode,maxPlayers:['free_flight','air_superiority'].includes(mode)?bounded(raw.maxPlayers,8,2,8):capacity,killLimit:bounded(raw.killLimit,3,0,50),scoreLimit:bounded(raw.scoreLimit,300,50,1000),matchDuration:mode==='free_flight'?0:bounded(raw.matchDuration,mode==='open_skies_coop'?900:600,0,3600),friendlyFire:mode==='open_skies_coop'?false:!!raw.friendlyFire,weaponsEnabled:mode==='free_flight'?false:raw.weaponsEnabled!==false,enemyRadar:raw.enemyRadar!==false,timeOfDay:['morning','midday','day','sunset','night'].includes(raw.timeOfDay)?raw.timeOfDay:'day',weather:['clear','cloudy','storm'].includes(raw.weather)?raw.weather:'clear',map:['aegis','frontier'].includes(raw.map)?raw.map:'aegis',difficulty:['easy','medium','hard'].includes(raw.difficulty)?raw.difficulty:'easy',seed:Number.isSafeInteger(raw.seed)?raw.seed>>>0:undefined,loadoutRule:'stock_equal_budget',missionPreset:raw.missionPreset&&validateMissionPreset(raw.missionPreset).ok?validateMissionPreset(raw.missionPreset).value:null};
}
export class Room {
  constructor(code,hostClient,options={}){this.code=code;this.hostId=hostClient.id;this.state='lobby';this.createdAt=Date.now();this.lastActivityAt=this.createdAt;this.options=safeOptions(options);this.players=new Map();this.match=null;this.tickInterval=null;this.countdownTimer=null;this.votes=new Map();this.pings=[];this.metrics={ticks:0,tickMs:0,maxTickMs:0,snapshots:0,bytesOut:0,droppedSnapshots:0};this.addPlayer(hostClient,hostClient.name||'Host Pilot');}
  addPlayer(client,name){
    if(this.players.size>=this.options.maxPlayers)return{success:false,reason:'Room is full'};
    if(!['lobby','in_game'].includes(this.state))return{success:false,reason:'Match is starting or finished'};
    const blue=[...this.players.values()].filter(p=>p.team==='blue').length,red=this.players.size-blue;
    const isHost=this.players.size===0||client.id===this.hostId;if(isHost)this.hostId=client.id;
    const p={id:client.id,ws:client.ws,name:name||`Pilot_${client.id.slice(0,4)}`,team:['open_skies_coop','free_flight'].includes(this.options.mode)?'blue':blue<=red?'blue':'red',jetModel:'x17',liveryId:'grey',ready:isHost,isHost,ping:client.ping||30,connected:true,reservedUntil:null,voice:false,loaded:false};this.players.set(p.id,p);client.roomCode=this.code;
    if(this.state==='in_game'&&this.match)this.match.initPlayer(p);else this.broadcastLobbyState();return{success:true,player:p};
  }
  disconnectPlayer(id,reservedUntil){const p=this.players.get(id);if(!p)return;p.connected=false;p.ws=null;p.reservedUntil=reservedUntil;p.ready=false;p.voice=false;this.match?.setConnected(id,false);this.electHost();this.broadcast({type:'player_disconnected',playerId:id,reservedUntil});this.broadcast({type:'voice_peer_left',id});this.cancelInvalidCountdown();this.broadcastLobbyState();}
  resumePlayer(client){const p=this.players.get(client.id);if(!p)return false;p.ws=client.ws;p.connected=true;p.reservedUntil=null;client.roomCode=this.code;this.match?.setConnected(p.id,true);this.electHost();this.broadcast({type:'player_reconnected',playerId:p.id});this.broadcastLobbyState();return true;}
  electHost(){const current=this.players.get(this.hostId);if(!current?.connected){const next=[...this.players.values()].find(p=>p.connected);if(next){this.hostId=next.id;next.ready=true;}}for(const p of this.players.values())p.isHost=p.id===this.hostId;}
  removePlayer(id){const p=this.players.get(id);if(!p)return;this.players.delete(id);this.votes.delete(id);this.match?.removePlayer(id);this.electHost();this.cancelInvalidCountdown();if(!this.players.size)this.cleanup();else{this.broadcast({type:'player_left',playerId:id,playerName:p.name});this.broadcast({type:'voice_peer_left',id});this.broadcastLobbyState();}}
  cancelInvalidCountdown(){if(this.state==='countdown'&&!this.rosterReady()){clearInterval(this.countdownTimer);this.countdownTimer=null;this.state='lobby';this.broadcast({type:'countdown_cancelled',reason:'Roster changed; check connected pilots, loading and teams'});}}
  connectedPlayers(){return [...this.players.values()].filter(p=>p.connected);}
  setPlayerReady(id,ready){if(this.state!=='lobby')return;const p=this.players.get(id);if(p){p.ready=!!ready;this.broadcastLobbyState();}}
  setPlayerTeam(id,team){if(this.state!=='lobby'||['open_skies_coop','free_flight'].includes(this.options.mode))return;const p=this.players.get(id);if(p&&['blue','red'].includes(team)){p.team=team;this.broadcastLobbyState();}}
  setPlayerAircraft(id,model,livery){if(this.state!=='lobby')return;const p=this.players.get(id);if(p){if(Object.hasOwn(JET_MODELS,model))p.jetModel=model;if(Object.hasOwn(LIVERIES,livery))p.liveryId=livery;this.broadcastLobbyState();}}
  updateSettings(id,settings){if(id!==this.hostId)return{success:false,reason:'Only the host can modify settings'};if(this.state!=='lobby')return{success:false,reason:'Cannot change settings during match'};if(settings.missionPreset&&!validateMissionPreset(settings.missionPreset).ok)return{success:false,reason:validateMissionPreset(settings.missionPreset).errors.join(' ')};const next=safeOptions(settings,this.options);if(this.players.size>next.maxPlayers)return{success:false,reason:'Too many players for that mode'};const changedMode=next.mode!==this.options.mode;this.options=next;if(changedMode){let i=0;for(const p of this.players.values()){p.team=['open_skies_coop','free_flight'].includes(next.mode)?'blue':i++%2?'red':'blue';p.ready=p.id===this.hostId;}}this.broadcastLobbyState();return{success:true};}
  vote(id,{mode,map}){if(!['lobby','post_match'].includes(this.state)||!this.players.get(id)?.connected||!MODES.includes(mode)||!['aegis','frontier'].includes(map))return false;const next=safeOptions({mode,map},this.options);if(this.players.size>next.maxPlayers)return false;this.votes.set(id,{mode,map});const total=this.connectedPlayers().length;const count=[...this.votes].filter(([pid,v])=>this.players.get(pid)?.connected&&v.mode===mode&&v.map===map).length;if(count>total/2){this.rematch();this.updateSettings(this.hostId,{mode,map});this.votes.clear();}this.broadcastLobbyState();return true;}
  rosterReady(){if(this.connectedPlayers().length<2||this.connectedPlayers().some(p=>!p.loaded||!p.ready&&p.id!==this.hostId)||this.connectedPlayers().length!==this.players.size)return false;if(!['open_skies_coop','free_flight'].includes(this.options.mode)){const teams=new Set(this.connectedPlayers().map(p=>p.team));if(teams.size<2)return false;}return true;}
  canStart(){return this.state==='lobby'&&this.rosterReady();}
  startCountdown(onStart){if(!this.canStart())return false;this.state='countdown';let count=3;this.broadcast({type:'countdown',count});this.countdownTimer=setInterval(()=>{if(!this.rosterReady()){this.cancelInvalidCountdown();return;}count--;if(count>0)this.broadcast({type:'countdown',count});else{clearInterval(this.countdownTimer);this.countdownTimer=null;this.startMatch();onStart?.();}},1000);this.countdownTimer.unref?.();return true;}
  startMatch(){if(this.tickInterval)clearInterval(this.tickInterval);this.state='in_game';this.match=new MatchState(this,this.options);for(const p of this.players.values())this.match.initPlayer(p);if(this.match.isCoop)this.match.ensureWingmen();for(const p of this.players.values())this.sendStart(p.id);let last=performance.now(),snapshotAccumulator=0;
    this.tickInterval=setInterval(()=>{if(this.state!=='in_game'||!this.match)return;const begin=performance.now(),elapsed=Math.min(.15,(begin-last)/1000);last=begin;this.match.tick(elapsed);this.metrics.ticks++;const cost=performance.now()-begin;this.metrics.tickMs=cost;this.metrics.maxTickMs=Math.max(this.metrics.maxTickMs,cost);snapshotAccumulator+=elapsed;if(snapshotAccumulator>=1/SNAPSHOT_HZ){snapshotAccumulator%=1/SNAPSHOT_HZ;this.metrics.snapshots++;this.broadcast({type:'snapshot',s:this.match.getSnapshot()},null,true);}if(this.match.status==='ended')this.endMatch(this.match.winner);},1000/SIMULATION_HZ);this.tickInterval.unref?.();}
  sendStart(id,extra={}){const p=this.players.get(id);if(p&&this.match)this.sendTo(id,{type:'game_started',protocol:PROTOCOL_VERSION,options:this.options,myTeam:p.team,myId:id,snapshot:this.match.getSnapshot(),...extra});}
  getResult(){const scoreboard=[...this.players.values()].map(p=>{const m=this.match?.players.get(p.id);return{id:p.id,name:p.name,team:p.team,model:p.jetModel,kills:m?.kills||0,deaths:m?.deaths||0,assists:m?.assists||0,damage:m?.damageDealt||0,score:m?.score||0,ping:p.ping};});return{type:'match_ended',epoch:this.match?.epoch,winner:this.match?.winner,scoreboard,teamScores:this.match?.teamScores,mission:this.match?.mission,zone:this.match?.zone,rewardId:this.match?.mission?.rewardId||null};}
  endMatch(winner){if(this.state==='post_match')return;this.state='post_match';clearInterval(this.tickInterval);this.tickInterval=null;this.broadcast(this.getResult());}
  rematch(){if(this.state==='in_game'||this.state==='countdown')return false;this.state='lobby';clearInterval(this.tickInterval);this.tickInterval=null;this.match=null;for(const p of this.players.values())p.ready=p.id===this.hostId;this.broadcastLobbyState();return true;}
  getLobbyState(){return{type:'lobby_update',protocol:PROTOCOL_VERSION,roomCode:this.code,hostId:this.hostId,state:this.state,options:this.options,votes:[...this.votes].map(([playerId,v])=>({playerId,...v})),players:[...this.players.values()].map(p=>({id:p.id,name:p.name,team:p.team,jetModel:p.jetModel,liveryId:p.liveryId,ready:p.ready,isHost:p.id===this.hostId,ping:p.ping,connected:p.connected,reservedUntil:p.reservedUntil,voice:p.voice,loaded:p.loaded}))};}
  broadcastLobbyState(){this.lastActivityAt=Date.now();this.broadcast(this.getLobbyState());}
  broadcast(message,excludeId=null,replaceable=false){for(const p of this.players.values())if(p.id!==excludeId)this.sendTo(p.id,message,replaceable);}
  sendTo(id,message,replaceable=false){const p=this.players.get(id);if(!p?.ws||p.ws.readyState!==1)return false;if(p.ws.bufferedAmount>MAX_BUFFERED_BYTES){if(replaceable){this.metrics.droppedSnapshots++;return false;}p.ws.close?.(1013,'Slow connection; reconnect to resume');return false;}try{const visible=message?.type==='snapshot'?{...message,s:this.match.snapshotFor(id,message.s)}:message?.type==='game_started'?{...message,snapshot:this.match.snapshotFor(id,message.snapshot)}:message;const raw=typeof visible==='string'?visible:JSON.stringify(visible);this.metrics.bytesOut+=Buffer.byteLength(raw);p.ws.send(raw);return true;}catch{return false;}}
  cleanup(){clearInterval(this.tickInterval);clearInterval(this.countdownTimer);this.tickInterval=null;this.countdownTimer=null;this.players.clear();this.match=null;this.votes.clear();}
}
